server {
    server_name pokemon.example.dev;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/pokemon.example.dev/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/pokemon.example.dev/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    # These three are critical for SSE
    proxy_buffering off;
    proxy_cache off;
    proxy_read_timeout 24h;   # keep the connection open; default 60s will kill it

    location / {
        proxy_pass http://localhost:3003;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
    }
    access_log  /var/log/nginx/pokemon.access.log;
}